Fix typos

diff --git a/playlist2links b/playlist2links
--- a/playlist2links
+++ b/playlist2links
@@ -8,7 +8,7 @@ fi
 URL="https://www.youtube.com/playlist?list=$1"
 
 TMPFILE=`mktemp /tmp/${tempfoo}.XXXXXX` || {
-	echo "Tempoprary file creation failuer" 1>&2
+	echo "Temporary file creation failed" 1>&2
 	exit 1
 }
 
